### ISSUE TITLE
Build fails on non-Windows machines

### ISSUE THREAD

**Issue by hugodahl** [FritzAndFriends/StreamDeckToolkit#11]
Currently, the build fails on macOS, and presumably, Linux as well, regardless of the build method. The errors come from the pre and post build step, which invokes PowerShell to stop and start the StreamDeck application. These operations are not valid on non-Windows PCs.

The steps should have an execution condition, allowing their execution only on Windows PCs.

**Comment by bradygaster** [comment]
I ran into this too, and I do not support the "ps1 only" approach, nor requiring customers to have to use PowerShell to do any of the build. It *should* be a fully .NET Core/Standard project that can be built on any platform without much build dependency. I'm going to tinker with this one for now but I'm unsure if I can get'er done.

**Comment by bradygaster** [comment]
@csharpfritz feel free to assign this one to me

**Comment by bradygaster** [comment]
This issue can be closed, as it addresses the build break but doesn't take into account actually enabling the build on Mac to work the same way it does on Windows. In addition, we can close PR #13, as though it *enabled the build* without throwing a build error, it doesn't enable all the requisite work as the original build.
