### ISSUE TITLE
Mac Dev needs some love

### ISSUE THREAD

**Issue by derekforeman** [FritzAndFriends/StreamDeckToolkit#133]
**Describe the bug**
The default template project does not run on MacOS. The build deploys and the process for the plugin appears to start, but does not execute.

**To Reproduce**

Start a new plugin project from the template, build and add plugin to stream deck. Execution fails.

**Expected behavior**
The plugin sample from the base template should *just* run. "F5" ready if you will. 

**Error Details**
The plugin fails with an error message from ConnectionManager line 66

> throw new ArgumentException($"{nameof(commandLineArgs)} must be the commandline args that the StreamDeck application calls this program with.");

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Version 10.14.1

**Additional context**
In comparison, in windows the template plugin *just works*. Open the solution/project, start debugging, add the plugin to the stream deck and BOOM!

**Comment by csharpfritz** [comment]
This looks like the same error I hit on Tuesday night in Windows, and is
probably related to the new ConfigBuilder not included in the template.


Jeff

**Comment by hugodahl** [comment]
I've run into other issues just trying to create and build a project on macOS from the template with just a simple `dotnet new`, so I took a stab at it tonight and got the template and build script issues resolved. PR forthcoming.

**Comment by csharpfritz** [comment]
Merged @hugodahl pull request
