### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by AlexHedley** [FritzAndFriends/StreamDeckToolkit#153]
What's the best way to debug the plugin?

Is it enough to add:

```csharp
public static void Main(string[] args)
{
#if DEBUG
   System.Diagnostics.Debugger.Launch(); 
#endif
    
   // code
}
```

p.s. I'll add it to Docs

**Comment by AlexHedley** [comment]
https://twitter.com/JamesMontemagno/status/1312097488627732481

> @JamesMontemagno Yes, there is a hook in the startup of the plugin that will trigger the debugger if you pass a "-break" command-line argument:

https://github.com/FritzAndFriends/StreamDeckToolkit/blob/dev/src/StreamDeckLib.Config/ConfigurationBuilder.cs#L19

**Comment by jamesmontemagno** [comment]
i could never figure it out. i need a video
