### ISSUE TITLE
Update the StreamDeckLib nuget with latest modifications

### ISSUE THREAD

**Issue by Maskime** [FritzAndFriends/StreamDeckToolkit#163]
**Describe the bug**
The `didReceiveGlobalSettings` never propagated to actions.

**To Reproduce**
1. Create a property_inspector that sends a `setGlobalSettings` instead of a `setSettings`
2. Create an `override` of the `OnDidReceiveGlobalSettings` method
3. Add some logs
4. Logs never show

**Expected behavior**
When overriding the method on an action, it should be called by the `ConnectionManager`

**Error Details**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I was able to pinpoint the issue to this : 
https://github.com/FritzAndFriends/StreamDeckToolkit/blob/dev/src/StreamDeckLib/ConnectionManager.cs#L186

In the lastest version of the code, this calls the `BroadcastMessage()` method, which should work. But in the code of the StreamDeckLib nuget (v0.4.480), it goes to:
```csharp
              if (string.IsNullOrWhiteSpace(msg.context) && string.IsNullOrWhiteSpace(msg.action))
              {
                ConnectionManager._Logger.LogInformation("System event received: $" + msg.Event);
                continue;
              }
```
Which make the ConnectionManager discard the call basically.
My guess then it's just that the StreamDeckLib code is out of sync with the nuget.

**Comment by csharpfritz** [comment]
I have a few fixes like this to put together and deploy, including updates to the .NET version of the templates and library.  I'll take a shot at this over the weekend

**Comment by Maskime** [comment]
:
