### ISSUE TITLE
Add Mac/Linux alternative for handling the manifest JSON

### ISSUE THREAD

**Issue by bradygaster** [FritzAndFriends/StreamDeckToolkit#18]
The build currently supports only Windows environments as it has hard-coded paths to the `C:\Program Files` path within a ps1 file. This will be different on Mac, but to fix it we should implement a similar approach as issue #17 (which is satisfied by PR #16). In #16, I created a `sh` file that stops the `Stream Deck` process in the same way as the original `ps1` file. So, this works on Mac and Linux. 

This issue will be considerably larger, however and will contain the following tweaks:

[ ] Figure out where Mac stores the plugins
[ ] Use the [jq](https://stedolan.github.io/jq/) library for doing the JSON parsing & querying
[ ] Use traditional bash syntax to do the file moves **or** up-level this as MSBuild copy tasks (though probably the former at first)

**Comment by csharpfritz** [comment]
not an issue with the PR that forces the ps1 files to only execute on Windows during the build process

**Comment by bradygaster** [comment]
fixed #40
