### ISSUE TITLE
README needs more information

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/StreamDeckToolkit#21]
The project readme needs to have more information added to describe the project, how to reference it, and how to use the template

**Comment by derekforeman** [comment]
A start of this is in PR #48

**Comment by hugodahl** [comment]
I'm working on a README that is more or less a "I `dotnet new`'d a project, now what?"

It outlines the purpose of the main files, suggests changes and updates (icon, dev details in `manifest.json`, things of that nature), including relevant links to the SDK docs. I'm aiming to have at least a completed draft for review & comments by tomorrow night.
