### ISSUE TITLE
Create a sample Property Inspector view

### ISSUE THREAD

**Issue by hugodahl** [FritzAndFriends/StreamDeckToolkit#24]
Create a sample property inspector (configuration pane) to add configuration, options, parameters, etc.

SDK Reference page: https://developer.elgato.com/documentation/stream-deck/sdk/property-inspector/
Sample code: https://developer.elgato.com/documentation/stream-deck/samples/pisamples/

**Comment by codingbandit** [comment]
I have something in the works for this
