### ISSUE TITLE
Have environment-specific runtime identifiers

### ISSUE THREAD

**Issue by hugodahl** [FritzAndFriends/StreamDeckToolkit#56]
Add runtime identifiers which will be used at build time based on the current build environment.

See [my comment here](https://github.com/FritzAndFriends/StreamDeckToolkit/pull/39#issuecomment-457802552) for a more detailed/thorough explanation of the apparent workings of the `<RuntimeIdentifier[s]>` elements.

**Comment by csharpfritz** [comment]
How best should we swap in the RuntimeIdentifier based on the platform a developer is working on?

Hmm....  thinking thinking...

**Comment by csharpfritz** [comment]
We got a suggestion from @benaadams on Twitter:  https://twitter.com/ben_a_adams/status/1089301629264973824

Looks do-able for a Debug configuration to force a single RuntimeIdentifier for the current OS.  For release configurations, force BOTH RuntimeIdentifiers

**Comment by hugodahl** [comment]
This was my stab at what should hopefully be, at least a first attempt at handling that situation

**Comment by csharpfritz** [comment]
Closed with PR #57
