### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/StreamDeckToolkit#73]
**Describe the bug**
There appears to be a memory leak in the stream deck library with applications remaining after the Stream Deck application is closed

**To Reproduce**
*Preferable*
src/SamplePlugin

*Alternatively*
1. Add custom plugin that uses StreamDeckLib to Stream Deck
2. Note the custom plugin running in Task Manager
3. Terminate the Stream Deck application
4. Custom plugin application is still running

**Expected behavior**
Custom plugin application should terminate

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by hugodahl** [comment]
I have a few thoughts on what might be happening in the template code, but most likely also applies from the sample code...

First, in the [`Program.cs`](https://github.com/FritzAndFriends/StreamDeckToolkit/blob/dev/Templates/StreamDeck.PluginTemplate.Csharp/content/Program.cs) has a call to [`Console.ReadLine()`](https://github.com/FritzAndFriends/StreamDeckToolkit/blob/dev/Templates/StreamDeck.PluginTemplate.Csharp/content/Program.cs#L68) at the end, after awaiting the call to `StartAsync()` for the plugin. When the plugin is running, there is no console, thus, no way for someone to hit the <kbd>Enter</kbd> key.

Second, the call to `Cancel()` on the `CancellationTokenSource` is only called after the plugin's execution, yet the plugin's exit condition is for the cancellation to be requested, meaning we're in a catch-22 situation.

Third and finally, the call to `Cancel()` of the token source should be driven by the state of the connection to the calling component, and not from the main application. This directly relates to the second issue I've mentioned above, regarding the call to the `Cancel()` method.

What is likely needed to help resolve the second and third issues, I believe, is to move the instantiation of the `CancellationTokenSource` into the `ConnectionManager` class, and have the `ConnectionManager` class monitor the state of the connection, or have a separate class (`IStreamDeckProxy`? Maybe another which is monitored by `IStreamDeckProxy` or `ConnectionManager`?) be the owner/operator of the `CancellationTokenSource`, and work with it as necessary based on the state of the connection.

**Comment by csharpfritz** [comment]
My thoughts as well... we'll discuss and dig into this on today's (Feb 1,
2019) stream


Jeff

**Comment by codingbandit** [comment]
Update - known issue - will be fixed in the next version of API

![image](https://user-images.githubusercontent.com/3979478/52362847-7c4fee80-2a0f-11e9-9429-540244151a6e.png)
