### ISSUE TITLE
Sample plugin and template should show how to support multiple actions

### ISSUE THREAD

**Issue by hugodahl** [FritzAndFriends/StreamDeckToolkit#92]
**Is your feature request related to a problem? Please describe.**
From the onset of the project, we've known that we need to support more than one action within the plugin. The code is beginning to get to the point where implementing support for this will be more complicated.

**Describe the solution you'd like**
An example of a plugin which implements and registers more than one action

**Describe alternatives you've considered**
The only alternatives are to roll/implement changes individually, or create one plugin project and directory per action.

**Additional context**
n/a

**Comment by hugodahl** [comment]
I've started some work on this, and have made some decent headway. Depending on circumstances, I should have something which can be reviewed, or at least discussed, by Friday's (Feb. 8th) stream.

**Comment by csharpfritz** [comment]
Completed
